# Generated by Django 3.1 on 2020-08-05 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_trucks.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='workday',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_trucks.workday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrate',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_trucks.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='truck',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_trucks.truck'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
