# Generated by Django 3.1 on 2020-08-27 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trucks', '0002_auto_20200805_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrate',
            options={'ordering': ['ini_date', 'id']},
        ),
        migrations.AddField(
            model_name='workday',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workday',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='end_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
