# Generated by Django 3.1 on 2020-08-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_trucks', '0005_auto_20200829_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrate',
            old_name='pay_rate',
            new_name='amount',
        ),
    ]
