# Generated by Django 3.1 on 2020-09-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trucks', '0007_auto_20200830_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='income',
            field=models.IntegerField(null=True),
        ),
    ]
