# Generated by Django 3.1 on 2020-09-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trucks', '0008_workday_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
